/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "D:\\desk\\bjcac\\jobsessionDocument\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "D:\\desk\\bjcac\\jobsessionDocument\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "D:\\desk\\bjcac\\jobsessionDocument\\node_modules\\vuepress-theme-vt\\plugins\\copy-code\\clientRootMixin.js"
import m3 from "D:\\desk\\bjcac\\jobsessionDocument\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]