/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\desk\\bjcac\\jobsessionDocument\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0f53fcf8",
    path: "/api/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f53fcf8").then(next)
    },
  },
  {
    path: "/api/index.html",
    redirect: "/api/"
  },
  {
    name: "v-6906316b",
    path: "/api/utils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6906316b").then(next)
    },
  },
  {
    name: "v-4f93c1a2",
    path: "/examples/disable-sidebar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f93c1a2").then(next)
    },
  },
  {
    name: "v-34768dcb",
    path: "/api/yuncunchu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34768dcb").then(next)
    },
  },
  {
    name: "v-7c33081f",
    path: "/examples/using-page-layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c33081f").then(next)
    },
  },
  {
    name: "v-02e3e07b",
    path: "/guide/database.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02e3e07b").then(next)
    },
  },
  {
    name: "v-3bb9c22a",
    path: "/guide/czh.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bb9c22a").then(next)
    },
  },
  {
    name: "v-f10d8d6a",
    path: "/guide/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f10d8d6a").then(next)
    },
  },
  {
    name: "v-0ed1142b",
    path: "/guide/databaseMethods.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ed1142b").then(next)
    },
  },
  {
    name: "v-11d2e8c4",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11d2e8c4").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-4fedf641",
    path: "/guide/guifan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fedf641").then(next)
    },
  },
  {
    name: "v-7649dccb",
    path: "/guide/reachBottom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7649dccb").then(next)
    },
  },
  {
    name: "v-385ffceb",
    path: "/guide/utils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-385ffceb").then(next)
    },
  },
  {
    name: "v-0d6b7171",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d6b7171").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-d0dd5dea",
    path: "/guide/yemianfuyong.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0dd5dea").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]